parser: '@typescript-eslint/parser'
extends:
  - airbnb-typescript
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
env:
  browser: true
  node: true
parserOptions:
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: detect
